FROM nginx:latest

# 설정 파일 복사
COPY nginx.conf /etc/nginx/nginx.conf
COPY certs /etc/nginx/certs
COPY dhparam.pem /etc/nginx/dhparam.pem

# SSL 인증서 권한 설정
RUN chmod 600 /etc/nginx/certs/*

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]