-- -- PostCategory 데이터 삽입
-- INSERT INTO PostCategory (posttype) VALUES ('Q_A');
-- INSERT INTO PostCategory (posttype) VALUES ('daily');
-- INSERT INTO PostCategory (posttype) VALUES ('introduction');
--
--
-- -- PetCategory 데이터 삽입
-- INSERT INTO pet_category (species,features,foodInfo,environment,playMethods,
--                           mustHaveItemFood,mustHaveItemToys,mustHaceItemCage,
--                           featureImagePath) VALUES ('토끼','a','a'
--                                                    ,'a','a','a',
--                                                     'a','a','a');

